Beth-Mardutho/hugoye-data

Data/TEI/h21v1n1brock.xml
Uploading a sample article for testing purposes
=> Article for testing

Data/TEI/h21n1brock.xml
Changed style of footnotes to inline notes
Also fixed typo in file name
=> Edited notes and file name

Data/TEI/h21n1brock.xml
changed h21v1n1 to h21n1 throughout the article, including the URI
specified in the file
=> Fixed other occurrences of file name

Data/TEI/h21n1brock.xml
=> Slight change

data/tei/h21n1brock.xml
Added pdf type on idno for testing PDF button
=> Added PDF idno type

data/tei/h21n1brock.xml
Adjusted idno URI for display purposes
=> Changed idno URI

data/tei/h21n1brock.xml
=> Updated URI idno

data/tei/Vol5No1/HV5N1Brock.xml
Changed some formatting from automatic conversion with XML template
=> Adjustments based on template

data/tei/Vol5No1/HV5N1Brock.xml
Using template on transformed document
=> Various adjustments

data/tei/h21n1prwalters.xml
=> Adding new file

data/tei/h21n1brock.xml, data/tei/h21n1prwalters.xml
Added type attribute on text element
Various other small changes for testing
=> Added type attribute

data/tei/HV5N1Brock.xml
Various elements cleaned up from automatic HTML conversion
=> Cleanup on html conversion

data/tei/HV12N1Brock.xml, data/tei/HV5N1Brock.xml
Fixing problem with PDF URI so that the download PDF button will appear
=> Adjusting pdf URI

data/tei/HV21N1CR-Amsterdam.xml
Fixing various aspects of the conference report test
=> Adjustments to Report

data/tei/HV21N1PRJuckel.xml
=> New book review

data/tei/HV21N1Penn.xml
sepearate <author> element for each author on multiple
=> Adjusted author format

data/tei/HV21N1Brock.xml, data/tei/HV21N1Kessel.xml, data/tei/HV21N1Penn.xml, data/tei/HV21N1Possekel.xml
added <biblScope> element to make items appear in order on volume display page
=> Testing order of appearance

data/tei/HV21N1CR-Amsterdam.xml
root uri did not have full address
=> Fixed typo in root uri

data/tei/HV10N1OBPetersen.xml, data/tei/HV5N1ADAtlas.xml, data/tei/HV5N1ADGorgiasPress.xml, data/tei/HV5N1FCMorgan.xml, data/tei/HV5N2ADAtlas.xml, data/tei/HV5N2AdAmazon.xml, data/tei/HV5N2FCSyrCOM2003.xml, data/tei/HV5N2FCSyrSym.xml, data/tei/HV5N2GEKiraz.xml, data/tei/HV6N1ADAmazon.xml, data/tei/HV6N1ADAtlas.xml, data/tei/HV6N1ADGorgiasPress.xml, data/tei/HV6N1ADRaffle.xml, data/tei/HV6N1FCCSSS.xml, data/tei/HV7N2CRPennVanRompay.xml, data/tei/HV7N2FCBibleofEdessa.xml, data/tei/HV8N1OBLane.xml, data/tei/HV8N1TurAbdinTour.xml, data/tei/HV9N2FCSyrBookofSteps.xml
Authors were left blank on these files
=> Adding authors

data/tei/HV13N1CRSBL.xml, data/tei/HV4N2CRPrayerSpirituality.xml, data/tei/hv15n1crintpatristics2011.xml, data/tei/hv17n2crqatar.xml, data/tei/hv19n2crchristians_middleeast.xml
=> Data cleanup

data/tei/HV19N1Baarda.xml, data/tei/HV19N1Bib-NewBooks.xml, data/tei/HV19N1Bib-Russian.xml, data/tei/HV19N1Burke_Ceplo.xml, data/tei/HV19N1Butts.xml, data/tei/HV19N1Francisco.xml, data/tei/HV19N2Borbone.xml, data/tei/HV19N2Korsvoll_Lied_Lund.xml, data/tei/HV19N2Moriggi.xml, data/tei/HV19N2Weltecke.xml, data/tei/hv19n1prbhayro.xml, data/tei/hv19n1prdickens.xml, data/tei/hv19n1prforness.xml, data/tei/hv19n1prgodwin.xml, data/tei/hv19n1prhorn.xml, data/tei/hv19n1prmaier.xml, data/tei/hv19n1prminets.xml, data/tei/hv19n1prwalters.xml, data/tei/hv19n2crallographic_traditions.xml, data/tei/hv19n2crchristians_middleeast.xml, data/tei/hv19n2prallen.xml, data/tei/hv19n2prvanrompay.xml
Testing order and issue display
=> Adding order number for volume 19

data/tei/HV21N1Brock.xml
=> Global footnote

data/tei/HV10N2Franzmann.xml, data/tei/HV10N2Healey.xml, data/tei/HV11N1Farag.xml, data/tei/HV11N1Farag_Lang.xml, data/tei/HV11N1Kitchen.xml, data/tei/HV11N1PRBrock.xml, data/tei/HV11N1Possekel.xml, data/tei/HV11N2Bucur.xml, data/tei/HV11N2Griffith.xml, data/tei/HV5N2Brock.xml, data/tei/HV5N2Martin.xml, data/tei/HV6N2Brock.xml, data/tei/HV6N2BurrisVanRompay.xml, data/tei/HV6N2Griffith.xml, data/tei/HV6N2Harrak.xml, data/tei/HV6N2Juckel.xml, data/tei/HV7N1IVSyriacSymAbstracts.xml, data/tei/HV7N1VanRompay.xml, data/tei/HV9N2Depuydt.xml, data/tei/HV9N2UpsonSaia.xml
https://github.com/Beth-Mardutho/hugoye-data/issues/125
=> Find and replace on bad URIs

data/tei/h17n1prgzella.xml, data/tei/h17n1prkeating.xml, data/tei/h17n1prlehto.xml, data/tei/h17n1prramelli.xml, data/tei/h17n1prwalters.xml, data/tei/h17n2prallen.xml, data/tei/h17n2prbhayro.xml, data/tei/h17n2prcarlson.xml, data/tei/h17n2prheal.xml, data/tei/h17n2prkessel.xml, data/tei/h17n2prmurrevandenberg.xml
Adding book reviews for vol 17
=> Vol. 17 reviews

data/tei/HV21N1CR-Amsterdam.xml
=> Fixing special characters display

data/tei/HV21N1CR-Amsterdam.xml
Trying to fugure out display issues with special characters
=> Adding xml encoding declaration

data/tei/HV21N1CR-Amsterdam.xml
changed encoding from UTF 8 to ISO 8859 to test display
=> Changed encoding

data/tei/HV21N1PRWalters.xml
=> Removing extra period from title

data/tei/HV21N1PRWalters.xml
=> Adding order number

data/tei/HV21N1Bib-Recent.xml, data/tei/HV21N1Bib-Russian.xml, data/tei/HV21N1PRWalters.xml
=> Vol 21 Bibliographies

data/tei/HV21N1Bib-Recent.xml, data/tei/HV21N1Bib-Russian.xml
Display errors from missing tags
=> Fixing errors in new files

data/tei/HV11N1Farag.xml
=> Editing transformed file

data/tei/HV11N1PRTaylor.xml
=> Editing file for display

data/tei/HV11N2Bucur.xml, data/tei/HV11N2PRGriffin.xml
=> Order and text type

data/tei/HV1N2Introduction.xml
One article had incorrect issue number
Also changing PDF link
=> Fixing order

data/tei/HV1N2Introduction.xml
=> Deleting excess material

data/tei/HV14N1ChatonnetDesreumaux1.xml, data/tei/HV14N1ChatonnetDesreumaux2.xml, data/tei/HV5N2AdGorgiasPress.xml, data/tei/HV6N2ADGorgiasPress.xml
Other issues of standard author names
=> Author standardization

data/tei/HV21N1Penn.xml
Aligning images and descriptions (again)
=> Images and descriptions

data/tei/HV21N1Penn.xml
=> Changing image type for file name

data/tei/HV17N1PRKitchen.xml, data/tei/HV17N2PRZieme.xml, data/tei/V17N2PRDickens.xml
Adding missing files from vol. 17
=> Missing files

data/tei/HV11N2PRKilroy.xml, data/tei/HV5N2FCSEERI.xml, data/tei/HV5N2Thekkeparambil.xml, data/tei/HV8N1OBLane.xml
Standardizing spelling of author name
=> Author name standardization

data/tei/HV21N1Kessel.xml, data/tei/HV21N1Penn.xml, data/tei/HV21N1Possekel.xml
Added page numbers
Fixed footnote ref numbers in Possekel
Added eGEDSH links
Fixed div organization in Penn
=> Page numbers, links

data/tei/hv20n1prbecker.xml, data/tei/hv20n1prcoakley.xml, data/tei/hv20n1prgodwin.xml, data/tei/hv20n1prvanrompay.xml, data/tei/hv20n1prwalsh.xml, data/tei/hv20n1prwalters.xml
=> FIxed PDF file name

data/tei/HV7N2Kiraz.xml
=> Fixing image links

data/tei/HV7N2Kiraz.xml
=> One more image link

data/tei/HV22N1Bertozzi.xml
Author name mistake between two files
=> Typo correction

data/tei/HV22N1Benfey.xml, data/tei/HV22N1Bertozzi.xml
Issue 22.1, fixing missing <div> tag in abstract that was causing a display issue.
=> Missing div in abstract

data/tei/HV22N2Maggi.xml, data/tei/HV22N2Mengozzi.xml, data/tei/HV22N2Mercz.xml, data/tei/HV22N2PRBarczok.xml, data/tei/HV22N2PRDickens.xml, data/tei/HV22N2PRKitchen.xml, data/tei/HV22N2PRWalters.xml, data/tei/HV22N2Walters.xml
Added text types
Also fixed URIs in reviews
=> Adjustments to 22.2

data/tei/HV22N2Walters.xml
=> Update Walters article

data/tei/HV22N2Walters.xml
=> More revisions to HV22N2Walters

data/tei/HV22N2Mengozzi.xml
=> Formating edits for HV22N2

data/tei/HV22N2PRBarczok.xml, data/tei/HV22N2PRDickens.xml, data/tei/HV22N2PRKitchen.xml, data/tei/HV22N2PRWalters.xml
Fixing error in file path adjustment for PDF downloads of book reviews in HV22n2
=> File path adjustment

data/tei/HV22N2Walters.xml
Full title was not displaying in HV22N2Walters
=> Fixed title

data/tei/HV22N2PRWalters.xml
=> Testing displaying book review titles in italics

data/tei/HV21N1PRHartung.xml, data/tei/HV21N1PRHunter.xml, data/tei/HV21N1PRJuckel.xml, data/tei/HV21N1PRKessel.xml, data/tei/HV21N1PRTreiger.xml, data/tei/HV21N1PRVanRompay.xml, data/tei/HV21N1PRWalters.xml, data/tei/HV21N2PRBird.xml, data/tei/HV21N2PRForness.xml, data/tei/HV21N2PRPenn.xml, data/tei/HV22N1PRChilders.xml, data/tei/HV22N1PRHartung.xml, data/tei/HV22N1PRWalters.xml, data/tei/HV22N2PRBarczok.xml, data/tei/HV22N2PRDickens.xml, data/tei/HV22N2PRKitchen.xml
=> Adding italics to book titles of books reviewed

data/tei/HV22N1Chesley.xml
Various adjustments and edits to some encoding errors in HV22N1Chesley
=> Edits to HV22N1Chesley

data/tei/HV10N1Kiraz.xml
Cleaned up file and added correct image code
=> Update Images HV10N1Kiraz

data/tei/HV5N1Mathews.xml, data/tei/HV6N1Mathews.xml
Fixing error with author name, resulting in duplicate entries in index
=> Author name adjustment - Mathews

data/tei/HV6N2Clocksin_Fernando.xml
=> File adjustment

data/tei/HV11N2Bcheiry.xml
found typo in title of an article
HV11N2Bcheiry was missing
=> FIxed typo and added missing file

data/tei/HV22N2PRKitchen.xml
=> Fixing typo

data/tei/HV23N1Butts.xml
Formatting corrections to HV23N1Butts
=> Round 1: Butts

data/tei/HV23N1Bib-Recent.xml, data/tei/HV23N1Bib-Russian.xml, data/tei/HV23N1Butts.xml, data/tei/HV23N1Kessel.xml, data/tei/HV23N1Muller-Kessler.xml, data/tei/HV23N1Nicosia.xml, data/tei/HV23N1PRAim.xml
Addressing various formatting issues
=> H23.1 Revisions Round 2

data/tei/HV23N1Muller-Kessler.xml
=> Final formatting issue

data/tei/HV23N1Bib-Recent.xml
=> Correcting typo

data/tei/HV23N1Muller-Kessler.xml
=> Adding editor's note

data/tei/hv18n1butts.xml
=> Adding encoded file

data/tei/hv18n1butts.xml
=> Fixing small issues with display

data/tei/HV18N1Crawford.xml
=> Adding new encoded text

data/tei/HV23N2Akhrass.xml, data/tei/HV23N2Akopian.xml, data/tei/HV23N2Hager.xml, data/tei/HV23N2Hilkens.xml, data/tei/HV23N2PRArzhanov.xml, data/tei/HV23N2PRFiano.xml, data/tei/HV23N2PRFinney.xml, data/tei/HV23N2PRHeal.xml
Replaced "unit" with "type" in biblScope description
=> Resolving display issue

data/tei/HV23N2Bibliographies_ChineseJapanese.xml, data/tei/HV23N2Hilkens.xml
Fixed:
-PDF not downloading on bibliography
-Bibliography display issue on Hilkens
=> Final revisions for 23.2

data/tei/HV23N2Akhrass.xml, data/tei/HV23N2Akopian.xml, data/tei/HV23N2Bibliographies_ChineseJapanese.xml, data/tei/HV23N2Hager.xml, data/tei/HV23N2Hilkens.xml, data/tei/HV23N2PRArzhanov.xml, data/tei/HV23N2PRFiano.xml, data/tei/HV23N2PRFinney.xml, data/tei/HV23N2PRHeal.xml
Fixed publication date for all files for 23.2
=> Revised publication date

data/tei/HV23N2PRHeal.xml
Adding n-dash instead of regular dash in biblScope for "How to cite"
=> Testing n-dash

data/tei/HV23N2Bibliographies_ChineseJapanese.xml
=> Fixing typo in HV23N2 Bibliographies

data/tei/HV23N2Hager.xml
Removing Karim from the Patriarch's name throughout
=> Removing Karim

data/tei/HV24N1Penn.xml
For some reason this file did not update with previous edits
=> Edits to penn images

data/tei/HV24N1PRPalmer.xml, data/tei/HV24N1PRVanRompay1.xml
=> Additional edits

data/tei/HV24N1PRPalmer.xml
Following some adjustments by Winona to the app for display issues
=> Updates to Palmer reveiw

data/tei/hv14n1prpalmer.xml, data/tei/hv15n1prpalmer.xml, data/tei/hv15n2prpalmer.xml
For Palmer reviews in Vol 14 and 15
=> Correcting PDF errors

data/tei/HV18N2Boero.xml
=> Typo in author name

data/tei/hv17n2mccollum.xml
=> Updating PDF file name

data/tei/HV24N2Lund.xml
=> Edit on Lund

data/tei/HV24N2PRVanRompay.xml
=> Edit Van Rompay review

data/tei/HV25N1Awa.xml
Missed one paragraph format on previous edit
=> One additional edit on Awa

data/tei/HV25N1Intro.xml, data/tei/HV25N1McConaughy.xml
=> George edits

data/tei/HV25N1Awa.xml, data/tei/HV25N1Intro.xml
=> Further edits

data/tei/HV25N1Awa.xml, data/tei/HV25N1Bib.xml, data/tei/HV25N1Intro.xml, data/tei/HV25N1McConaughy.xml, data/tei/HV25N1PRCalabro.xml, data/tei/HV25N1PRChen.xml, data/tei/HV25N1PRHarvey.xml, data/tei/HV25N1PRKitchen.xml, data/tei/HV25N1PRMazzola.xml, data/tei/HV25NJutkiewicz.xml, data/tei/HV25NMuehlberger.xml
Date of issue was still 2021 instead of 2022
=> Fixing date

data/tei/HV25N2Freeman.xml, data/tei/HV25N2Kiraz.xml, data/tei/HV25N2Minets.xml, data/tei/HV25N2PRAim.xml, data/tei/HV25N2PRCoakley.xml, data/tei/HV25N2PRDelcogliano.xml, data/tei/HV25N2PRGibson.xml, data/tei/HV25N2PRMinets.xml, data/tei/HV25N2Zimbardi-Chamourgiotaki.xml
Correcting issues in visual layout
=> Layout edits

data/tei/HV25N2Freeman.xml, data/tei/HV25N2PRAim.xml, data/tei/HV25N2PRCoakley.xml, data/tei/HV25N2PRDelcogliano.xml, data/tei/HV25N2PRGibson.xml, data/tei/HV25N2PRMinets.xml
Finalizing small issues with display
Added <head> tag to the book title at the top of reviews to try to fix the left column spacing.
=> Other small edits

data/tei/HV26N1Bcheiry.xml, data/tei/HV26N1Bib.xml, data/tei/HV26N1Bunce.xml, data/tei/HV26N1Kessel1.xml, data/tei/HV26N1PRWalters.xml
=> Round 2 of edits

data/tei/HV26N1Bunce.xml, data/tei/HV26N1OBBadwi.xml
Primarily fixing issues with Syriac text display in Bunce article
=> Further formatting issues

data/tei/HV26N1Kessel1.xml, data/tei/HV26N1Kessel2.xml
Fixing capitalization issues in titles
=> Standardizing title capitalization

data/tei/HV26N2Innemee.xml, data/tei/HV26N2Jackel.xml, data/tei/HV26N2Minov.xml
Fixing repetition of colon in title display
=> Title edits

data/tei/HV27N1Butts.xml, data/tei/HV27N1Gomiero.xml, data/tei/HV27N1Jamali.xml, data/tei/HV27N1Stadel.xml
=> Adding articles
